model : "gpt-3.5-turbo-instruct"
model_name : "microsoft/Phi-3-mini-128k-instruct"

temperature : 1
max_tokens: 200
prompt : "Rephrase your answer based only on the information provided in the answers given in a coherent phrase without saying based on the information"
    